name: 'npm publish'
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 20.14.0
          registry-url: https://registry.npmjs.org
      - name: publish
        run: |
          npm run build:package
          cp package.json dnd/dist
          cd dnd/dist
          ls
