name: 'npm publish'
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Startup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.14.0
          registry-url: https://registry.npmjs.org

      - name: Make package
        run: |
          npm ci
          npm run build:package
          node make-package.js
          cp README.md ./dnd/dist/README.md
          cd dnd
          rm -rf dist/types
          tar -czvf artifact.tgz dist

      - name: Publish to NPM
        run: 'npm publish ./dnd/artifact.tgz'
        env:
          NODE_AUTH_TOKEN: ${{ secrets. NPM_TOKEN }}
