name: 'npm publish'
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Startup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.14.0
          registry-url: https://registry.npmjs.org

      - name: Make package
        run: |
          npm ci
          npm run build:package
          node make-package.js
          cd dnd
          cd dist
          ls
          cat package.json
